name: sifra_env
channels:
  - conda-forge
  - anaconda
  - marufr
dependencies:
  - anaconda-client=1.1.2=py27_0
  - clyent=1.0.0=py27_0
  - colorama=0.3.3=py27_0
  - cycler=0.9.0=py27_0
  - decorator=4.0.4=py27_0
  - freetype=2.5.5=0
  - icu=56.1=0
  - ipython=4.0.0=py27_0
  - ipython_genutils=0.1.0=py27_0
  - jbig=2.1=0
  - jpeg=8d=0
  - libgfortran=1.0=0
  - libpng=1.6.17=0
  - libtiff=4.0.6=1
  - matplotlib=1.5.0=np110py27_0
  - mkl=11.3.1=0
  - networkx=1.10=py27_0
  - numexpr=2.5=np110py27_0
  - numpy=1.10.1=py27_0
  - openblas=0.2.14=3
  - openssl=1.0.2d=0
  - pandas=0.17.1=np110py27_0
  - path.py=8.1.2=py27_0
  - pexpect=3.3=py27_0
  - pickleshare=0.5=py27_0
  - pillow=3.0.0=py27_1
  - pip=9.0.1=py27_0
  - ptyprocess=0.5=py27_0
  - pydot=1.0.28=py27_0
  - pyparsing=1.5.6=py27_0
  - pyqt=4.11.4=py27_0
  - python=2.7.10=2
  - python-dateutil=2.4.2=py27_0
  - pytz=2015.7=py27_0
  - pyyaml=3.11=py27_1
  - qt=4.8.7=1
  - readline=6.2=2
  - requests=2.8.1=py27_0
  - scikit-learn=0.17=np110py27_1
  - scipy=0.16.0=np110py27_1
  - seaborn=0.7.1=py27_0
  - setuptools=27.2.0=py27_0
  - simplegeneric=0.8.1=py27_0
  - sip=4.16.9=py27_0
  - six=1.10.0=py27_0
  - sqlite=3.9.2
  - tk=8.5.18=0
  - traitlets=4.0.0=py27_0
  - wheel=0.26.0=py27_1
  - xlrd=0.9.4=py27_0
  - xz=5.0.5=0
  - yaml=0.1.6=0
  - zlib=1.2.8=0
  - pip:
    - actdiag==0.5.1
    - alabaster==0.7.7
    - babel==2.1.1
    - blockdiag==1.5.3
    - brewer2mpl==1.4.1
    - couchdb==1.1
    - docutils==0.12
    - funcparserlib==0.3.6
    - ipython-genutils==0.1.0
    - jinja2==2.8
    - lmfit==0.9.2
    - markupsafe==0.23
    - nwdiag==1.0.0
    - parmap==1.2.3
    - pybtex==0.19
    - pybtex-docutils==0.2.1
    - pygments==2.1
    - pygraphviz==1.3.1
    - python-igraph==0.7.1.post6
    - seqdiag==0.9.0
    - snowballstemmer==1.2.1
    - sphinx==1.3.6
    - sphinx-rtd-theme==0.1.9
    - sphinxcontrib-actdiag==0.6.0
    - sphinxcontrib-bibtex==0.3.3
    - sphinxcontrib-blockdiag==1.5.5
    - sphinxcontrib-nwdiag==0.7.0
    - sphinxcontrib-seqdiag==0.6.0
    - webcolors==1.5

